
mysqlhost: 'localhost'
mysqlport: '3306'
mysqluser: 'System'
mysqlpass: 'Updater'
mysqldb: 'mistspad'

antipumkin: 'false'
convertedchainname: 'Chain Ring'

randomeventrewardid:
    - 266
    - 264
