name: MistsOfYsir
main: moy.tollenaar.stephen.MistsOfYsir.MoY
version: B.1.8
authors: [guitargun]
description: the ultimate plugin
depend: [MistCore] 

commands: 
     party:
             description: make a party
             usage: /<command>
     skill:
             description: opens the skill inventory
             usage: /<command>
     qnpc:
             description: main command for the npc systems
             usage: /<command>
     lvl:
             description: just a test
             usage: /<command>
     event:
             description: event parameters
             usage: /<command> 
     quest:
             description: lets you see the quests quests
             usage: /<command>		 
     harbor:
             description: these are the waiting locations
             usage: /<command>
     trip:
             description: these are the waiting locations
             usage: /<command>
     speechtrait:
             description: needed for quests
             usage: /<command>
     library:
             description: shows the readed books
             usage: /<command>			 